# -*- coding: utf-8 -*-
"""Exercise 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aN61qiK7kQIi21gxEgPyWZD5tvmZLDHJ
"""

import pandas as pd

df=pd.read_csv("inventory_dataset.csv")

df

df.isnull().sum()

df["Purchase_Price"]=df["Purchase_Price"].fillna(df["Purchase_Price"].median())

df["Sale_Price"]=df["Sale_Price"].fillna(df["Sale_Price"].mean())

df.isnull().sum()

df.dropna(inplace=True)

df.isnull().sum()

y=df["Sale_Price"]

import matplotlib.pyplot as plt
plt.plot(y)
plt.show()

q1=df["Sale_Price"].quantile(0.25)
q3=df["Sale_Price"].quantile(0.75)
print(q1)
print(q3)

iqr=q3-q1
print(iqr)
lb=q1-(1.5*iqr)
ub=q3+1.5*iqr
print(lb)
print(ub)

import numpy as np
x_sale=np.reshape(df["Sale_Price"],-1)
print(x_sale)

outlier=((x_sale<lb)|(x_sale>ub))

outlier

cleaned=df[~outlier]

cleaned

x=cleaned["Sale_Price"]
plt.plot(x)
plt.show()

from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
cleaned["Quantity_In_Stock"]=scaler.fit_transform(cleaned[["Quantity_In_Stock"]])

print(cleaned["Quantity_In_Stock"])

def toint(x):
   return int(x)

cleaned["Quantity_In_Stock"]=cleaned["Quantity_In_Stock"].apply(toint)

print(cleaned["Quantity_In_Stock"])

print(cleaned)

from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(sparse_output=False)
one_hot_encoded = encoder.fit_transform(cleaned[["Discontinued"]])



print(one_hot_encoded)

cleaned.drop("Discontinued",axis=1,inplace=True)

one_hot=pd.DataFrame(one_hot_encoded)
print(one_hot)

one_hot.drop(1,axis=1,inplace=True)

print(one_hot)

print(cleaned)

cleaned.reset_index(drop=True)

one_hot.shape

cleaned.shape

df=pd.concat([cleaned.reset_index(drop=True),one_hot.reset_index(drop=True)],axis=1)

print(df)

from google.colab import files

df.to_csv('df.csv')
files.download('df.csv')